kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: budget-v1
  labels:
    app: budget-v1
    app.kubernetes.io/component: budget-v1
    app.kubernetes.io/instance: budget-v1
    app.kubernetes.io/part-of: bee-travels
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 200m
        memory: 256Mi
    activeDeadlineSeconds: 21600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: budget-v1
    deploymentconfig: budget-v1
  template:
    metadata:
      labels:
        app: budget-v1
        deploymentconfig: budget-v1
    spec:
      containers:
        - name: budget-v1
          image: maxshapiro32/budget-v1:latest
          ports:
            - containerPort: 9006
              protocol: TCP
          env:
            - name: HOST_IP
              value: budget-v1
            - name: LOG_LEVEL
              value: info
            - name: PORT
              value: '9006'
            - name: SCHEME
              value: http
            - name: HOTEL_URL
              value: 'http://hotel-v1:9101'
            - name: CAR_URL
              value: 'http://carrental-v1:9102'
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 256Mi
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
